import { useEffect, useMemo, useState } from "react";

type Role = "SUPER_ADMIN" | "COMPETIDOR" | "ORGANIZADOR" | "ARBITRO" | string;
type UserType = "COMPETIDOR" | "ORGANIZADOR" | "ARBITRO";
type View = "home" | "roleRegister" | "login" | "panel";
type Option = { id: string; name: string; sportId?: string };
const API_BASE = import.meta.env.VITE_API_URL ?? "/api"; const TOKEN_KEY = "competidoreya_token";
const decode = (t: string): { email?: string; role?: Role } => { try { return JSON.parse(atob(t.split(".")[1] || "")); } catch { return {}; } };

export function App() {
const [view,setView]=useState<View>("home"); const [selectedRole,setSelectedRole]=useState<UserType| null>(null); const [token,setToken]=useState<string|null>(localStorage.getItem(TOKEN_KEY));
const [firstName,setFirstName]=useState(""); const [lastName,setLastName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
const [countryId,setCountryId]=useState(""); const [cityId,setCityId]=useState(""); const [message,setMessage]=useState("");
const [countries,setCountries]=useState<Option[]>([]); const [cities,setCities]=useState<Option[]>([]); const [sports,setSports]=useState<Option[]>([]); const [categories,setCategories]=useState<Option[]>([]); const [tournaments,setTournaments]=useState<any[]>([]); const [matches,setMatches]=useState<any[]>([]);
const [tournamentName,setTournamentName]=useState(""); const [sportId,setSportId]=useState(""); const [categoryIds,setCategoryIds]=useState<string[]>([]); const [slots,setSlots]=useState("16"); const [startDate,setStartDate]=useState(""); const [endDate,setEndDate]=useState("");
const user=useMemo(()=>token?decode(token):{},[token]); const filteredCategories=useMemo(()=>categories.filter(c=>c.sportId===sportId),[categories,sportId]);
const fetchJson=async(path:string,options?:RequestInit)=>{const res=await fetch(`${API_BASE}${path}`,options);const data=await res.json().catch(()=>({}));return{res,data}};
const loadCities=async(c:string)=>{const {res,data}=await fetchJson(`/cities${c?`?countryId=${c}`:""}`); if(res.ok)setCities(data)};

useEffect(()=>{void (async()=>{const [a,b,c]=await Promise.all([fetchJson('/countries'),fetchJson('/sports'),fetchJson('/sport-categories')]); if(a.res.ok)setCountries(a.data); if(b.res.ok)setSports(b.data); if(c.res.ok)setCategories(c.data);})();},[]);
useEffect(()=>{if(!token||view!=="panel")return; void (async()=>{const h={Authorization:`Bearer ${token}`}; const [t,m]=await Promise.all([fetchJson('/tournaments',{headers:h}), fetchJson('/matches/assigned',{headers:h})]); if(t.res.ok)setTournaments(t.data); if(m.res.ok)setMatches(m.data);})();},[token,view]);

const register = async (role: UserType) => { const endpoint = role==="COMPETIDOR"?"/auth/register/competitor":role==="ORGANIZADOR"?"/auth/register/organizer":"/auth/register/referee"; const r=await fetchJson(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firstName,lastName,countryId,cityId,email,password})}); setMessage(r.res.ok?"Cuenta creada. Ahora iniciá sesión.":r.data.message||"Error al registrar"); if(r.res.ok) setView('login'); };

return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-bold">CompetidoresYa</h1>
{!token&&view==='home'&&<section className="mt-8 grid gap-4 md:grid-cols-3">{(['COMPETIDOR','ORGANIZADOR','ARBITRO'] as UserType[]).map(r=><button key={r} className="rounded-lg border bg-white p-4" onClick={()=>{setSelectedRole(r);setView('roleRegister')}}>{r}</button>)}<button className="rounded border px-4 py-2 md:col-span-3" onClick={()=>setView('login')}>Iniciar sesión</button></section>}
{!token&&view==='roleRegister'&&selectedRole&&<form className="mt-6 max-w-lg space-y-3 rounded bg-white p-4 shadow" onSubmit={(e)=>{e.preventDefault(); void register(selectedRole);}}><h2 className="text-xl font-semibold">Registro {selectedRole}</h2><input className="w-full rounded border p-2" placeholder="Nombre" value={firstName} onChange={e=>setFirstName(e.target.value)} required/><input className="w-full rounded border p-2" placeholder="Apellido" value={lastName} onChange={e=>setLastName(e.target.value)} required/><input className="w-full rounded border p-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="w-full rounded border p-2" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><select className="w-full rounded border p-2" value={countryId} onChange={e=>{setCountryId(e.target.value);setCityId(''); void loadCities(e.target.value)}} required><option value="">País</option>{countries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="w-full rounded border p-2" value={cityId} onChange={e=>setCityId(e.target.value)} required><option value="">Ciudad</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="w-full rounded bg-blue-600 px-4 py-2 text-white" type="submit">Crear cuenta</button></form>}
{!token&&view==='login'&&<form className="mt-6 max-w-md space-y-3 rounded bg-white p-4 shadow" onSubmit={async e=>{e.preventDefault(); const {res,data}=await fetchJson('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}); if(!res.ok)return setMessage(data.message||'Credenciales inválidas'); localStorage.setItem(TOKEN_KEY,data.token); setToken(data.token); setView('panel');}}><h2 className="text-xl">Login</h2><input className="w-full rounded border p-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="w-full rounded border p-2" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="w-full rounded bg-blue-600 px-4 py-2 text-white">Ingresar</button></form>}
{token&&view==='panel'&&<section className="mt-6 space-y-4 rounded bg-white p-4 shadow"><h2 className="text-xl font-semibold">Panel {user.role}</h2>
{user.role==='ORGANIZADOR'&&<div className="space-y-2"><h3 className="font-medium">Crear torneo</h3><input className="w-full rounded border p-2" placeholder="Nombre torneo" value={tournamentName} onChange={e=>setTournamentName(e.target.value)}/><select className="w-full rounded border p-2" value={sportId} onChange={e=>setSportId(e.target.value)}><option value="">Deporte</option>{sports.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="w-full rounded border p-2" value={cityId} onChange={e=>setCityId(e.target.value)}><option value="">Ciudad</option>{cities.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div className="grid grid-cols-2 gap-2">{filteredCategories.map(c=><label key={c.id}><input type="checkbox" checked={categoryIds.includes(c.id)} onChange={e=>setCategoryIds(v=>e.target.checked?[...v,c.id]:v.filter(x=>x!==c.id))}/> {c.name}</label>)}</div><input className="w-full rounded border p-2" type="number" value={slots} onChange={e=>setSlots(e.target.value)}/><input className="w-full rounded border p-2" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/><input className="w-full rounded border p-2" type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/><button className="rounded bg-emerald-600 px-3 py-2 text-white" onClick={async()=>{const h={'Content-Type':'application/json',Authorization:`Bearer ${token}`}; const {res,data}=await fetchJson('/tournaments',{method:'POST',headers:h,body:JSON.stringify({name:tournamentName,sportId,cityId,slots:Number(slots),startDate,endDate,categoryIds})}); setMessage(res.ok?'Torneo creado':data.message||'Error creando torneo');}}>Guardar torneo</button><h3 className="font-medium">Inscriptos</h3>{tournaments.map(t=><div key={t.id} className="rounded border p-2">{t.name} - {(t.registrations||[]).length} inscriptos</div>)}</div>}
{user.role==='ARBITRO'&&<div><h3 className="font-medium">Partidos asignados</h3><p className="text-sm">Estado en preparación.</p>{matches.map(m=><div key={m.id} className="rounded border p-2">{m.tournament?.name} - {m.result ?? 'Sin resultado'}</div>)}</div>}
{user.role==='COMPETIDOR'&&<div><h3 className="font-medium">Torneos disponibles</h3>{tournaments.map(t=><div key={t.id} className="rounded border p-2">{t.name}</div>)}</div>}
<button className="rounded border px-3 py-2" onClick={()=>{localStorage.removeItem(TOKEN_KEY);setToken(null);setView('home')}}>Cerrar sesión</button></section>}
{!!message&&<p className="mt-4 text-sm">{message}</p>}</div></main>;
}
